### PR TITLE
Add zh_CN translate

### PR DESCRIPTION
**Pull request by madoka773**

### CODE REVIEW

**Comment by nlogozzo** [comment]
Even if you aren't translating the docs module, could you please add this language to NickvisionTubeConverter.Shared/Docs/po/LINGUAS and create a po file there as well...

**Comment by madoka773** [comment]
done

**Review by nlogozzo — APPROVED** [review]

**Comment by nlogozzo** [comment]
Thanks!

**Comment by nlogozzo** [comment]
Question...Weblate is complaining that zh_CN and zh_Hans are both Chinese simplified. Would you be able to merge these translations into one or remove zh_Hans if it is inadequate?

**Comment by madoka773** [comment]
zh_CN is the correct Chinese Simplified language code.
So I think zh_ Hans need to be deleted.

```
madoka@fedora:~$ echo $LANG
zh_CN.UTF-8
madoka@fedora:~$ 
```

If zh_ Hans, the only way I can see the translation is through this

`flatpak run --env="LC_ALL=zh_Hans.UTF-8" org.nickvision.tubeconverter`

**Comment by nlogozzo** [comment]
Ok I'll remove it. Thanks

**Pull request merged**
