### PR TITLE
Bug fixes + tiny improvements

### LINKED ISSUE #729: Debug page in the About section shows `psutil` missing
Psutil isn't used any more but the debug page still searches for it.

### LINKED ISSUE #746: Error notification has "Open File" action
Hi,
when a download fails, due to permissions or something, the shown desktop notification still offers to open the file.

Version: 2023.12.0

### PR DESCRIPTION
**Pull request by JoseBritto**
Fixes #746  
Fixes #729

### CODE REVIEW

**Comment by JoseBritto** [comment]
Im not sure if #711 should be considered fixed. Right now it downloads in AV1 if and only if there is a format option that has av1 and the same extension chosen. 
For example consider `https://youtu.be/uGS6BdmUU1c`
This video if we do --list-formats gives:
```
ID      EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
sb2     mhtml 48x27        0    │                  mhtml │ images                                  storyboard
sb1     mhtml 80x45        0    │                  mhtml │ images                                  storyboard
sb0     mhtml 160x90       0    │                  mhtml │ images                                  storyboard
233     mp4   audio only        │                  m3u8  │ audio only          unknown             [en] Default
234     mp4   audio only        │                  m3u8  │ audio only          unknown             [en] Default
139-drc m4a   audio only      2 │   12.79MiB   49k https │ audio only          mp4a.40.5   49k 22k [en] low, DRC, m4a_dash
139     m4a   audio only      2 │   12.79MiB   49k https │ audio only          mp4a.40.5   49k 22k [en] low, m4a_dash
249     webm  audio only      2 │   13.22MiB   50k https │ audio only          opus        50k 48k [en] low, webm_dash
250     webm  audio only      2 │   15.64MiB   60k https │ audio only          opus        60k 48k [en] low, webm_dash
140-drc m4a   audio only      2 │   33.95MiB  129k https │ audio only          mp4a.40.2  129k 44k [en] medium, DRC, m4a_dash
140     m4a   audio only      2 │   33.95MiB  129k https │ audio only          mp4a.40.2  129k 44k [en] medium, m4a_dash
251     webm  audio only      2 │   28.69MiB  109k https │ audio only          opus       109k 48k [en] medium, webm_dash
602     mp4   256x144     15    │ ~ 24.27MiB   93k m3u8  │ vp09.00.10.08   93k video only
394     mp4   256x144     30    │   11.08MiB   42k https │ av01.0.00M.08   42k video only          144p, mp4_dash
269     mp4   256x144     30    │ ~ 52.21MiB  199k m3u8  │ avc1.4D400C    199k video only
160     mp4   256x144     30    │    9.84MiB   38k https │ avc1.4D400C     38k video only          144p, mp4_dash
603     mp4   256x144     30    │ ~ 41.01MiB  156k m3u8  │ vp09.00.11.08  156k video only
278     webm  256x144     30    │   15.11MiB   58k https │ vp09.00.11.08   58k video only          144p, webm_dash
395     mp4   426x240     30    │   15.39MiB   59k https │ av01.0.00M.08   59k video only          240p, mp4_dash
229     mp4   426x240     30    │ ~ 76.40MiB  291k m3u8  │ avc1.4D4015    291k video only
133     mp4   426x240     30    │   15.64MiB   60k https │ avc1.4D4015     60k video only          240p, mp4_dash
604     mp4   426x240     30    │ ~ 76.13MiB  290k m3u8  │ vp09.00.20.08  290k video only
242     webm  426x240     30    │   19.32MiB   74k https │ vp09.00.20.08   74k video only          240p, webm_dash
396     mp4   640x360     30    │   29.46MiB  112k https │ av01.0.01M.08  112k video only          360p, mp4_dash
230     mp4   640x360     30    │ ~164.21MiB  626k m3u8  │ avc1.4D401E    626k video only
134     mp4   640x360     30    │   28.33MiB  108k https │ avc1.4D401E    108k video only          360p, mp4_dash
18      mp4   640x360     30  2 │ ≈ 62.07MiB  237k https │ avc1.42001E         mp4a.40.2       44k [en] 360p
605     mp4   640x360     30    │ ~149.95MiB  572k m3u8  │ vp09.00.21.08  572k video only
243     webm  640x360     30    │   34.45MiB  131k https │ vp09.00.21.08  131k video only          360p, webm_dash
397     mp4   854x480     30    │   51.12MiB  195k https │ av01.0.04M.08  195k video only          480p, mp4_dash
231     mp4   854x480     30    │ ~213.90MiB  816k m3u8  │ avc1.4D401F    816k video only
135     mp4   854x480     30    │   40.98MiB  156k https │ avc1.4D401F    156k video only          480p, mp4_dash
606     mp4   854x480     30    │ ~236.99MiB  904k m3u8  │ vp09.00.30.08  904k video only
244     webm  854x480     30    │   47.46MiB  181k https │ vp09.00.30.08  181k video only          480p, webm_dash
398     mp4   1280x720    30    │   91.82MiB  350k https │ av01.0.05M.08  350k video only          720p, mp4_dash
232     mp4   1280x720    30    │ ~381.80MiB 1456k m3u8  │ avc1.4D401F   1456k video only
136     mp4   1280x720    30    │   70.64MiB  269k https │ avc1.4D401F    269k video only          720p, mp4_dash
609     mp4   1280x720    30    │ ~434.20MiB 1656k m3u8  │ vp09.00.31.08 1656k video only
247     webm  1280x720    30    │   84.56MiB  323k https │ vp09.00.31.08  323k video only          720p, webm_dash
399     mp4   1920x1080   30    │  174.34MiB  665k https │ av01.0.08M.08  665k video only          1080p, mp4_dash
270     mp4   1920x1080   30    │ ~  1.27GiB 4951k m3u8  │ avc1.640028   4951k video only
137     mp4   1920x1080   30    │  262.70MiB 1002k https │ avc1.640028   1002k video only          1080p, mp4_dash
614     mp4   1920x1080   30    │ ~741.65MiB 2829k m3u8  │ vp09.00.40.08 2829k video only
248     webm  1920x1080   30    │  239.54MiB  914k https │ vp09.00.40.08  914k video only          1080p, webm_dash
616     mp4   1920x1080   30    │ ~  1.46GiB 5695k m3u8  │ vp09.00.40.08 5695k video only          Premium
```
That is the av01 option is only available in the mp4 format and not the webm. So, the prefer av1 option only downloads av1 if the chosen format is mp4. I see that we have functionality to convert videos, maybe we should use that? I'm not sure how it works. Since the option is 'prefer av1' not and 'only download av1', this behavior would be acceptable I think.

**Review by nlogozzo — CHANGES_REQUESTED** [review]

**Comment by JoseBritto** [comment]
[f3ec008](https://github.com/NickvisionApps/Parabolic/pull/769/commits/f3ec00832352efd23ec02b5aa2d01f6057029d36) needs to be tested. I couldn't figure out what I'm missing to build for windows. Is it even possible from linux?

Here is a video: https://www.youtube.com/watch?v=Pv0iVoSZzN8&pp=ygUIbXIgYmVhc3Q%3D

@nlogozzo I hope tiny improvements like this would be ok here. We can merge this pr later when you have time to properly go through everything.

**Comment by nlogozzo** [comment]
> Is it even possible from linux?

No 😅 I have a KVM setup with Windows to compile and push the Windows apps...

**Comment by nlogozzo** [comment]
Everything looks good, I saw let's say for #711 for when the whole download engine gets rewritten in the C++ rewrite soon

**Review by nlogozzo — APPROVED** [review]

**Pull request merged**
