### PR TITLE
Docs - Fix failing build because of missing docs

### PR DESCRIPTION
**Pull request by fsobolev**

### CODE REVIEW

**Comment by nlogozzo** [comment]
Can you double check the LINGUAS file for me I don't think it was sorted alphabetically...

**Comment by fsobolev** [comment]
> Can you double check the LINGUAS file for me I don't think it was sorted alphabetically...

I don't really get why Weblate doesn't keep LINGUAS ordered and why it sometimes creates useless "Update translations files" commits...

**Comment by nlogozzo** [comment]
Yeah idk why either...

**Comment by nlogozzo** [comment]
Yeah idk why either...

**Pull request merged**
