### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Nickvision Parabolic/App](https://hosted.weblate.org/projects/nickvision-tube-converter/app/).

It also includes following components:

* [Nickvision Parabolic/Docs](https://hosted.weblate.org/projects/nickvision-tube-converter/docs/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by nlogozzo** [comment]
@fsobolev Could you DocsUpdateYelp/Html for me?

**Comment by fsobolev** [comment]
> @fsobolev Could you DocsUpdateYelp/Html for me?

Maybe it worth only do this before releases? It's not like document translations affect anything.

**Comment by nlogozzo** [comment]
> And sure I could update them, I just suggest to not waste time when it's not required.

That's fine...I just remember when a new language was added (in this case `fi`) CI failed until docs had yelp and html pages...but this time looks like it works 🤷‍♂️

**Comment by fsobolev** [comment]
> That's fine...I just remember when a new language was added (in this case fi) CI failed until docs had yelp and html pages...but this time looks like it works man_shrugging

Ideally we need a bot to do this stuff 😄

**Pull request merged**
